Issue 4 proper handling of k 1 encoding
ronomon/reed-solomon pull request #5
Opened 2018-08-09 08:20 UTC by maximelubin

Encoding the single parity of k+1 code is XORing all data parts with the existing, potentially random and uninitialized content of the parity buffer.

Do a copy first, then XOR all the rest.

2018-08-09 08:59 UTC, lamphamsy approved these changes

2018-08-13 06:55 UTC, jorangreef requested changes

2018-08-13 06:55 UTC, jorangreef commented on binding.cc
> +            dot_xor(shards[i], target, shardSize);
Would you please update the indentation before `dot_xor()` to be the same as the indentation before `dot_cpy()`?

Indentation should use 2 spaces, no tabs.

2018-08-13 06:55 UTC, jorangreef commented on test.js
> +  var parity = Node.crypto.randomBytes(parityOffset + paritySize);
Please would you use this instead:

`var parity = cipher.update(Buffer.alloc(parityOffset + paritySize));`

The AES cipher is faster than a call to `crypto.randomBytes()`, saving around 2 seconds (10%) of total runtime, for the same guarantees.

2018-08-13 06:55 UTC, jorangreef commented on test.js
> -      var key = '';
Thanks for removing this artifact.

2018-08-13 06:55 UTC, jorangreef commented on test.js
> +  [24, 6,  3,  1, 164320, 'f2fad94fdb9e4518728cb0a5a5dbe392'],
Would you please remove the trailing comma that was added here?

2018-08-13 06:55 UTC, jorangreef commented
Thanks @maximelubin , I made the requested PR changes already in another PR:

https://github.com/ronomon/reed-solomon/commit/6f23d45c0c0a10fa5032a5d1ce6536a92c601186

2018-08-13 06:55 UTC, closed without merging